spring:
  application:
    name: backend
  profiles:
    active: prod

server:
  port: 80

postgres:
  servername: localhost
  port: 5432
  database: postgres
  username: postgres
  password: root

mail:
  host: smtp.gmail.com
  port: 587
  username: <>
  password: <>