spring:
  application:
    name: backend
  profiles:
    active: prod

server:
  port: 80

postgres:
  servername: localhost
  port: 5432
  database: startracker
  username: postgres
  password: startracker

mail:
  host: smtp.gmail.com
  port: 587
  username: <>
  password: <>